from typing import Any, Optional, Protocol, runtime_checkable

from app.sandbox.manager import SandboxExecutor, sandbox_executor


@runtime_checkable
class RuntimeBackend(Protocol):
    name: str
    kind: str
    description: str

    def describe(self) -> dict[str, Any]: ...
    def get_thread_workspace(self, thread_id: str) -> str: ...
    def get_workspace_dir(self, thread_id: str) -> str: ...
    def get_outputs_dir(self, thread_id: str) -> str: ...
    def get_uploads_dir(self, thread_id: str) -> str: ...
    def resolve_workspace_path(self, thread_id: str, rel_path: str) -> str | None: ...
    def resolve_outputs_path(self, thread_id: str, rel_path: str) -> str | None: ...
    def get_file_history(self, thread_id: str, path: str | None = None, limit: int = 50) -> list[dict]: ...
    async def execute_python(self, code: str, timeout: Optional[int] = None, thread_id: Optional[str] = None) -> dict: ...
    async def execute_javascript(self, code: str, timeout: Optional[int] = None, thread_id: Optional[str] = None) -> dict: ...
    async def execute_bash(self, command: str, timeout: Optional[int] = None, thread_id: Optional[str] = None) -> dict: ...
    async def write_file(self, path: str, content: str, thread_id: str) -> dict: ...
    async def read_file(self, path: str, thread_id: str) -> dict: ...
    async def list_files(self, path: str = ".", thread_id: str = "") -> dict: ...
    async def write_file_bytes(self, path: str, data: bytes, thread_id: str) -> dict: ...
    async def read_file_bytes(self, path: str, thread_id: str) -> dict: ...
    async def save_output(self, filename: str, content: str, thread_id: str) -> dict: ...
    def is_shadow_thread(self, thread_id: str) -> bool: ...
    def create_shadow_workspace(self, base_thread_id: str, shadow_thread_id: str) -> dict: ...
    def get_shadow_info(self, shadow_thread_id: str) -> dict | None: ...
    def list_shadow_changes(self, shadow_thread_id: str) -> dict: ...
    def get_shadow_diff(self, shadow_thread_id: str, *, context_lines: int = 3, max_diff_chars: int = 20_000) -> dict: ...
    def accept_shadow_workspace(self, shadow_thread_id: str, paths: list[str] | None = None, hunks: list[dict] | None = None) -> dict: ...
    def discard_shadow_workspace(self, shadow_thread_id: str) -> bool: ...


class SandboxDelegatingRuntimeBackend:
    def __init__(self, *, name: str, kind: str, description: str, sandbox: SandboxExecutor | None = None):
        self.name = name
        self.kind = kind
        self.description = description
        self._sandbox = sandbox or sandbox_executor

    def __getattr__(self, item: str):
        return getattr(self._sandbox, item)
